FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1 

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install flask gunicorn vosk

COPY . .

EXPOSE 2002

CMD ["gunicorn", "--bind", "0.0.0.0:2002", "main:app"]

